import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SearchContext } from "./context/SearchContext";
import Header from "./components/Header";
import Footer from "./components/Footer";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Next Application",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SearchContext>
          <Header />
          {children}
          <Footer />
        </SearchContext>
      </body>
    </html>
  );
}
